### ISSUE TITLE
500 error during multipart/form-data send unexpected file param name (with sails)

### ISSUE THREAD

**Issue by cgalibern** [theganyo/swagger-node-runner#41]
If I try to upload unexpected file name param I get a 500 error, I expected a 400 Bad Request instead
Perhaps I am missing something ?

Example:

``` shell
$ curl -F "badfilename=@s" --header 'Content-Type: multipart/form-data' 'http://localhost:1337/hello' -v
*   Trying ::1...
* Connected to localhost (::1) port 1337 (#0)
> POST /hello HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 240
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------7a61cdece2908f90
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials:
< Access-Control-Allow-Methods:
< Access-Control-Allow-Headers:
< Access-Control-Expose-Headers:
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 1476
< Date: Thu, 09 Jun 2016 05:44:22 GMT
< Connection: keep-alive
* HTTP error before end of send, stop sending
<
Error: Unexpected field<br> &nbsp; &nbsp;at makeError (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/multer/lib/make-error.js:12:13)<br> &nbsp; &nbsp;at wrappedFileFilter (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/multer/index.js:39:19)<br> &nbsp; &nbsp;at Busboy.&lt;anonymous&gt; (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/multer/lib/make-middleware.js:112:7)<br> &nbsp; &nbsp;at emitMany (events.js:127:13)<br> &nbsp; &nbsp;at Busboy.emit (events.js:201:7)<br> &nbsp; &nbsp;at Busboy.emit (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/busboy/lib/main.js:31:35)<br> &nbsp; &nbsp;at PartStream.&lt;anonymous&gt; (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/busboy/lib/types/multipart.js:213:13)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at PartStream.emit (events.js:188:7)<br> &nbsp; &nbsp;at HeaderParser.&lt;anonymous&gt; (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/dicer/lib/Dicer.js:51:16)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at HeaderParser.emit (events.js:188:7)<br> &nbsp; &nbsp;at HeaderParser._finish (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/dicer/lib/HeaderParser.js:68:8)<br> &nbsp; &nbsp;at SBMH.&lt;anonymous&gt; (/Users/cgaliber/dev/bugs/upload-swagger-sails/node_modules/dicer/lib/HeaderParser.js:40:12)<br> &nbsp; &nbsp;at emitMany (events.js:127:13)<br> &nbsp; &nbsp;at SBMH.emit (events.js:201:7)
* Closing connection 0
```

Here is the error from node console

``` text
      Error: Unexpected field
      at makeError (node_modules/multer/lib/make-error.js:12:13)
      at wrappedFileFilter (node_modules/multer/index.js:39:19)
      at Busboy.<anonymous> (node_modules/multer/lib/make-middleware.js:112:7)
      at emitMany (events.js:127:13)
      at Busboy.emit (events.js:201:7)
      at Busboy.emit (node_modules/busboy/lib/main.js:31:35)
      at PartStream.<anonymous> (node_modules/busboy/lib/types/multipart.js:213:13)
      at emitOne (events.js:96:13)
      at PartStream.emit (events.js:188:7)
      at HeaderParser.<anonymous> (node_modules/dicer/lib/Dicer.js:51:16)
      at emitOne (events.js:96:13)
      at HeaderParser.emit (events.js:188:7)
      at HeaderParser._finish (node_modules/dicer/lib/HeaderParser.js:68:8)
      at SBMH.<anonymous> (node_modules/dicer/lib/HeaderParser.js:40:12)
      at emitMany (events.js:127:13)
      at SBMH.emit (events.js:201:7)
```

Here is an extract of swagger.yaml parameters section

``` yaml
      parameters:
        - name: stdout
          in: formData
          description: the file to upload
          required: false
          type: "file"
```

**Comment by cgalibern** [comment]
[find a code example here](https://github.com/cgalibern/swagger-node-runner-issue-41)

[you can reproduce using following gist](https://gist.github.com/cgalibern/babb1328d31e4fe03d6d30454aedae1b)

```shell
git clone https://github.com/cgalibern/swagger-node-runner-issue-41
cd swagger-node-runner-issue-41
npm install
./node_modules/.bin/sails lift &
sleep 15
npm run upload-failure
```

Output example:
```text 
> upload-swagger-sails@0.0.0 upload-failure
> .
> curl -F 'badfilename=@app.js' --header 'Content-Type:
> multipart/form-data' http://localhost:1337/hello -v

*   Trying ::1...
* Connected to localhost (::1) port 1337 (#0)
> POST /hello HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 2007
> Expect: 100-continue
> Content-Type: multipart/form-data;
> boundary=------------------------537ddd543f42fb9b
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials:
< Access-Control-Allow-Methods:
< Access-Control-Allow-Headers:
< Access-Control-Expose-Headers:
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 1476
< Date: Thu, 09 Jun 2016 06:13:10 GMT
< Connection: keep-alive
* HTTP error before end of send, stop sending
<
Error: Unexpected field<br> &nbsp; &nbsp;at makeError (./node_modules/multer/lib/make-error.js:12:13)<br>
&nbsp; &nbsp;at wrappedFileFilter (./node_modules/multer/index.js:39:19)<br>
&nbsp; &nbsp;at Busboy.&lt;anonymous&gt; (./node_modules/multer/lib/make-middleware.js:112:7)<br>
&nbsp; &nbsp;at emitMany (events.js:127:13)<br> &nbsp; &nbsp;at Busboy.emit (events.js:201:7)<br>
&nbsp; &nbsp;at Busboy.emit (./node_modules/busboy/lib/main.js:31:35)<br>
&nbsp; &nbsp;at PartStream.&lt;anonymous&gt; (./node_modules/busboy/lib/types/multipart.js:213:13)<br>
&nbsp; &nbsp;at emitOne (events.js:96:13)<br>
&nbsp; &nbsp;at PartStream.emit (events.js:188:7)<br>
&nbsp; &nbsp;at HeaderParser.&lt;anonymous&gt; (./node_modules/dicer/lib/Dicer.js:51:16)<br>
&nbsp; &nbsp;at emitOne (events.js:96:13)<br>
&nbsp; &nbsp;at HeaderParser.emit (events.js:188:7)<br>
&nbsp; &nbsp;at HeaderParser._finish (./node_modules/dicer/lib/HeaderParser.js:68:8)<br>
&nbsp; &nbsp;at SBMH.&lt;anonymous&gt; (./node_modules/dicer/lib/HeaderParser.js:40:12)<br>
&nbsp; &nbsp;at emitMany (events.js:127:13)<br>
&nbsp; &nbsp;at SBMH.emit (events.js:201:7)
* Closing connection 0
```

**Comment by cgalibern** [comment]
@theganyo is it an existing issue ?

**Comment by theganyo** [comment]
I'm not aware of it. Could it be an issue in multer or your multer settings?

Scott

**Comment by cgalibern** [comment]
@theganyo I didn't set any multer options, only what is provided in the git issue example: https://github.com/cgalibern/swagger-node-runner-issue-41

I only set parameters into swagger.yaml setting

I think the error {"code":"LIMIT_UNEXPECTED_FILE","field":"badfilename","storageErrors":[]} 
should be treated as a 400 bad parameter by swagger node

what to you think about PR https://github.com/theganyo/swagger-node-runner/pull/43 ?

Cyril

**Comment by junyong08** [comment]
@cgalibern try change "badfilename" to "file"

**Comment by Javier1177** [comment]
How did you fix this problem?

**Comment by cgalibern** [comment]
@Javier1177 PR #43 fixed this
