### ISSUE TITLE
204 No Content - Mocked mode

### ISSUE THREAD

**Issue by facundovictor** [theganyo/swagger-node-runner#91]
I know this may be related to the [Issue 79](https://github.com/theganyo/swagger-node-runner/issues/79), and it's not my intention to replicate it, but to avoid deviating the conversation in the main thread. Of course, if you think it should go within  [Issue 79](https://github.com/theganyo/swagger-node-runner/issues/79), please let me know and I'll add a reference in the  [Issue 79](https://github.com/theganyo/swagger-node-runner/issues/79).

**Version**:
`"_id": "swagger-node-runner@0.7.2"`

**Resume**:
Running swagger in mock mode (`-m`), and executing a `DELETE` method that should return `204 (no content)` on success, will fail (500 Internal Server Error):

```javascript
TypeError: Cannot read property 'getExample' of undefined
    at swagger_router (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/swagger-node-runner/fittings/swagger_router.js:120:51)
    at Runner.<anonymous> (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/bagpipes/lib/bagpipes.js:171:7)
    at bound (domain.js:280:14)
    at Runner.runBound (domain.js:293:12)
    at Runner.pipeline (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/pipeworks/pipeworks.js:72:17)
    at Runner.flow (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/pipeworks/pipeworks.js:223:19)
    at Pipeworks.flow (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/pipeworks/pipeworks.js:135:17)
    at Pipeworks.siphon (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/pipeworks/pipeworks.js:186:19)
    at Runner.<anonymous> (/home/fvictor/Workspace/git_repos/swagger-express/node_modules/bagpipes/lib/bagpipes.js:98:22)
    at bound (domain.js:280:14)
```

**How to reproduce it?:**
As an example, I'm building the next `DELETE` method:

```yaml
paths:
  /client/{id}:
    delete:
      # Controller
      operationId: deleteClient
      description: Removes the client that corresponds to the identifiers (if exists).
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
```

As you know, from [w3 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5): 
> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

And from the [Swagger Specification](http://swagger.io/specification/#response-object-58), it's clear that the schema shouldn't be present if we have to return no body (i.e. no content):

| Field Name | Type | Description |
| --- | --- | --- |
| schema | Schema Object | A definition of the response structure. It can be a primitive, an array or an object. **If this field does not exist, it means no content is returned as part of the response.** As an extension to the Schema Object, its root type value may also be "file". This SHOULD be accompanied by a relevant produces mime-type. |

Now, try running `swagger project start -m` with that endpoint defined and you'll get the error.

---
**My Thoughts**:

IMHO, I think that, as the swagger mock mode should help for building the controller tests first, and for developing the front-end side, this should work without adding a mocked controller for fixing this issue.

Also, I'm seeing that the mock code demands to have defined the request property `_mockreturnstatus`, as it's not defined, the statusCode defaults to 200. As the operation doesn't have defined an answer with a 200 code, [it will return undefined](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/swagger_router.js#L120). Am I doing something wrong?

```javascript
    if (mockMode) {

      var statusCode = parseInt(context.request.get('_mockreturnstatus')) || 200;

      var mimetype = context.request.get('accept') || 'application/json';
      var mock = operation.getResponse(statusCode).getExample(mimetype);

      if (mock) {
        debug('returning mock example value', mock);
      } else {
        mock = operation.getResponse(statusCode).getSample();
        debug('returning mock sample value', mock);
      }

      context.headers['Content-Type'] = mimetype;
      context.statusCode = statusCode;

      return cb(null, mock);
    }
```

And even solving that, the library `sway` [won't find a schema to fake](https://github.com/apigee-127/sway/blob/master/lib/types/response.js#L103):

```javascript
Response.prototype.getSample = function () {
  var sample;

  if (!_.isUndefined(this.definitionFullyResolved.schema)) {
    sample = helpers.getJSONSchemaMocker()(this.definitionFullyResolved.schema);
  }

  return sample;
};
```

And this is OK, because the answer should have `no content`, and the schema isn't specified.
The swagger runner won't end the response, and the [bagpipes library won't end the response right there either.](https://github.com/apigee-127/bagpipes/blob/2d1ed02f0f0b4aa6600640a7db980211314af9ae/lib/bagpipes.js#L208)... and we're back to [Issue 79](https://github.com/theganyo/swagger-node-runner/issues/79).

So far, I'm adding a mocked controller like:
```javascript
function deleteClient (req, res) {
   // TODO: do more mocked stuff with a mocked param
   res.sendStatus(204);
}
```

But, IMHO, if the idea is to quickly have a fake API to start working with, and only from the swagger specifications, we shouldn't have to write mocked controllers for simple requests like this one. Am I missing something?

**Comment by ath88** [comment]
I have the same problem. It would be nice to not have to build mock controllers to have 204 work.
